version: 2.1
orbs:
  node: circleci/node@4.1

jobs:
  lint:
    docker:
      - image: cimg/node:12.18.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint Code
          command: |
            yarn lint
  unit:
    docker:
      - image: cimg/node:12.18.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Unit Tests
          command: |
            echo "Hello World"

workflows:
  pr:
    jobs:
      - lint
      - unit
